# Trigger on pushes to the main branch.
# Authenticate with Azure using a service connection.
# Deploy resources defined in an ARM template.

name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: 'Azure CLI Login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy ARM Templates'
      run: |
        echo "Deploying ARM templates..."
        az deployment group create \
          --resource-group healthcare-dev-rg \
          --template-file arm/adf-template.json \
          --parameters arm/adf-parameters.json

    - name: 'Deploy Linked Services'
      run: |
        echo "Deploying linked services..."
        az deployment group create \
          --resource-group healthcare-dev-rg \
          --template-file arm/linked_services_template.json