# Trigger on pushes to the main branch.
# Authenticate with Azure using a service connection.
# Deploy resources defined in an ARM template.

name: Deploy to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'arm/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: 'Azure CLI Login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy Storage Account'
      run: |
        echo "Deploying Storage Account..."
        az deployment group create \
          --resource-group healthcare-dev-rg \
          --template-file arm/adls_storage_account.json

    - name: 'Deploy Azure Data Factory'
      run: |
        echo "Deploying Azure Data Factory..."
        az deployment group create \
          --resource-group healthcare-dev-rg \
          --template-file arm/adf-template.json \
          --parameters arm/adf-parameters.json

    - name: 'Deploy Linked Services'
      run: |
        echo "Deploying Linked Services..."
        az deployment group create \
          --resource-group healthcare-dev-rg \
          --template-file arm/linked_services_template.json

    - name: 'Deploy ADLS Linked Service'
      run: |
        echo "Deploying Linked Service for ADLS..."
        az deployment group create \
          --resource-group healthcare-dev-rg \
          --template-file arm/adls_linked_service.json

    - name: 'Deploy Datasets'
      run: |
        echo "Deploying Datasets..."
        az deployment group create \
          --resource-group healthcare-dev-rg \
          --template-file arm/datasets.json

    - name: 'Deploy Copy Pipeline'
      run: |
        echo "Deploying Copy Pipeline..."
        az deployment group create \
          --resource-group healthcare-dev-rg \
          --template-file arm/copy_pipeline.json

